import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import NAV from "../components/Nav";
import Hero from "../components/Intro";
import Fight from "../components/Fight";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>SnowDay</title>
        <meta
          content="Generated by API3"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <NAV />
        <Hero />
        <Fight />
      </main>

      {/* <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
